name: CI

env:
  CI: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2

    - name: Install MSYS2
      uses: eine/setup-msys2@v1
      with:
        update: true
        cache: true
        install: "autoconf git make mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-SDL2_ttf"

    - name: Download Gambit Scheme
      uses: daviwil/download-gambit@v1
      with:
        os: win-mingw
        repo: daviwil/gambit
        branch: build-gambit-patched
        workflow-name: Build Gambit
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Tests
      run: ./test.sh

    - name: Build Code
      run: ./build.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: crash-the-stack-win-x64
        path: dist/

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SDL2
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev

    - name: Download Gambit Scheme
      uses: daviwil/download-gambit@v1
      with:
        repo: daviwil/gambit
        branch: build-gambit-patched
        workflow-name: Build Gambit
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Tests
      run: ./test.sh

    - name: Build Code
      run: ./build.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: crash-the-stack-linux-x64
        path: dist/

  macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SDL2
      run: brew install pkg-config sdl2 sdl2_image sdl2_ttf

    - name: Download Gambit Scheme
      uses: daviwil/download-gambit@v1
      with:
        repo: daviwil/gambit
        branch: build-gambit-patched
        workflow-name: Build Gambit
        artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

    - name: Run Tests
      run: ./test.sh

    - name: Build Code
      run: |
        ./scripts/macos/create-app.sh
        ./build.sh

        mkdir dist/app
        mv dist/crash-the-stack.app dist/app

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: crash-the-stack-macos-x64
        path: dist/app

  Itch-Upload:
    runs-on: ubuntu-latest
    needs: [Windows, Linux, macOS]
    if: success() && github.event_name == 'push'

    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2

    - name: Download Butler
      run: |
        wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -V

    - name: Upload Artifacts to Itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        # Upload Windows build
        ./butler push ./crash-the-stack-win-x64 fluxharmonic/crash-the-stack:windows-dev

        # Upload Linux build
        ./butler push ./crash-the-stack-linux-x64 fluxharmonic/crash-the-stack:linux-dev

        # Upload macOS build
        ./butler push ./crash-the-stack-macos-x64 fluxharmonic/crash-the-stack:macos-dev
